### ISSUE TITLE
RTL8211F 协商速率问题

### ISSUE THREAD

**Issue by talpachen** [nickfox-taterli/zynq-board1#2]
搞了一些板子回来，做了部分测试和分析，[见此](https://github.com/vllogic/vllink_zynq7ext/blob/main/board_ZYNQ7_MB_V01/interface.md)
自带固件网口只能协商100M，根据网上零散消息，网口芯片在无初始化时能自动协商，依此测试，速率还是100M。

1.05V上补两个4.7uF电容，无变化。

**Comment by nickfox-taterli** [comment]
大兄弟还搞了扩展板,我直接把网线剥皮飞线上去的,焊了几次都协商10//100,有说是feedback线路不好,主处理器没能正确处理,没验证.
